Hounslow-Connect/frontend

- aws/core.yml
- aws/lambda.yml
https://trello.com/c/b0uq24cc
Updated deploy scripts
NA
NA
> Changed project name in cloudformation

- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Footer/Footer.tsx
- src/components/Header/Header.tsx
- src/components/Search/Search.tsx
- src/views/DutyToRefer.tsx
- src/views/Favourites/Favourites.tsx
- src/views/Referral/Referral.tsx
- src/views/Referral/Steps/TermsAndConditions.tsx
- src/views/Service/Service.tsx
https://trello.com/c/b0uq24cc
London eu-west-2 is now working so move back to there
NA
NA
> Linted code

- src/components/Link/Link.tsx
- src/views/Service/ButtonCard/ButtonCard.tsx
- src/views/Service/ContactCard/ContactCard.tsx
- src/views/Service/CostCard/CostCard.tsx
- src/views/Service/CriteriaCard/CriteriaCard.scss
- src/views/Service/CriteriaCard/CriteriaCard.tsx
- src/views/Service/GalleryCard/GalleryCard.scss
- src/views/Service/GalleryCard/GalleryCard.tsx
- src/views/Service/LocationCard/LocationCard.scss
- src/views/Service/LocationCard/LocationCard.tsx
- src/views/Service/ReferralCard/ReferralCard.tsx
- src/views/Service/Service.scss
- src/views/Service/Service.tsx
> Various service page responsive tweaks

- src/components/Breadcrumb/Breadcrumb.scss
- src/components/Header/Header.scss
Made global header styling tweaks
N/A
N/A
> Added global header styling tweaks

- src/components/Link/Link.tsx
- src/views/Results/MapView/MapView.tsx
- src/views/Service/ButtonCard/ButtonCard.tsx
- src/views/Service/ContactCard/ContactCard.tsx
- src/views/Service/CostCard/CostCard.tsx
- src/views/Service/CriteriaCard/CriteriaCard.scss
- src/views/Service/CriteriaCard/CriteriaCard.tsx
- src/views/Service/GalleryCard/GalleryCard.scss
- src/views/Service/GalleryCard/GalleryCard.tsx
- src/views/Service/LocationCard/LocationCard.scss
- src/views/Service/LocationCard/LocationCard.tsx
- src/views/Service/ReferralCard/ReferralCard.tsx
- src/views/Service/Service.scss
- src/views/Service/Service.tsx
> Feature/service page UI tweaks

- src/views/About.tsx
- src/views/Results/Results.scss
> Amended search results filter styling

- src/components/Banner/Banner.scss
- src/components/Banner/Banner.tsx
- src/components/Personas/Personas.scss
- src/components/PersonasCard/PersonasCard.scss
- src/components/PersonasCard/PersonasCard.tsx
> Made styling tweaks to homepage persona cards

- src/views/Service/GalleryCard/GalleryCard.tsx
Added class to single gallery card layout
N/A
N/A
> Amended gallery card layout

- src/components/Button/Button.scss
- src/components/Search/Search.scss
https://trello.com/c/Tj6E8777
N/A
N/A
> Increased icon size on category buttons

- src/components/Button/Button.scss
- src/components/FeedbackModal/FeedbackModal.tsx
- src/components/Search/Search.tsx
- src/views/Service/RelatedServices/RelatedServicesCard/RelatedServicesCard.tsx
- src/views/Service/Service.scss
https://trello.com/c/fYKdzPS8
https://trello.com/c/Je8yOq6Z
N/A
N/A
> Added disclaimer text to feedback modal

- package.json
- src/App.tsx
- src/assets/images/icons/home-screen-icon.svg
- src/components/HomeScreenPrompt/HomeScreenPrompt.scss
- src/components/HomeScreenPrompt/HomeScreenPrompt.tsx
- src/components/HomeScreenPrompt/InstructionModal/InstructionModal.scss
- src/components/HomeScreenPrompt/InstructionModal/InstructionModal.tsx
- src/components/HomeScreenPrompt/InstructionModal/index.ts
- src/components/HomeScreenPrompt/index.ts
- yarn.lock
https://trello.com/c/7u1LKP3Q
N/A
N/A
> Added home screen prompt component

- package.json
- tsconfig.json
- yarn.lock
Updated react-scripts package for required security updates
> Updated react-scripts to latest version for security updates

- package.json
- src/components/CategoryList/CategoryList.tsx
- src/views/Results/MapView/icons.tsx
- yarn.lock
Small bugfix PR for img imports using require
N/A
N/A
> Updated require img import in CategoryList and Map icons

- src/views/Results/Filters/Category.tsx
Added dynamic images to collection pages
N/A
N/A
> Output dynamic collection images

- src/components/Banner/Banner.tsx
> Add a hidden text inside empty buttons that is visible to screen-readers

- src/components/Button/Button.scss
- src/hooks/forceUpdateHook.js
- src/views/Service/Service.scss
- src/views/Service/Service.tsx
- src/views/Service/ShareCard/ShareCard.tsx
> revised responsive design for the share card action buttons

- src/hooks/forceUpdateHook.js
> removed unused variables to prevent violating tslint rules

- src/views/Service/MapCard/MapCard.tsx
- src/views/Service/Service.tsx
> allow icon type for service MapCard to be passed in as a prop

- src/views/Service/CriteriaCard/CriteriaCard.scss
- src/views/Service/CriteriaCard/CriteriaCard.tsx
- src/views/Service/Service.scss
> resolved responsive padidng issue

- src/views/Service/Service.tsx
> return eligibilities on service page based on the order key

- src/components/LinkButton/LinkButton.tsx
- src/stores/organisationStore.ts
- src/views/Organisation/Organisation.scss
- src/views/Organisation/Organisation.tsx
- src/views/Service/Service.scss
- src/views/Service/Service.tsx
> updated layout on services page as per wireframes

- src/views/Service/Service.tsx
> fixed lint errors

- src/stores/searchStore.ts
> only show enabled categories and personas

- src/stores/resultsStore.ts
- src/views/Results/Filters/ParamsFilter/ParamsFilter.tsx
> updated default distance to 1 mile

- .travis.yml
> change before deploy

- public/index.html
- src/App.tsx
- src/components/CookieBanner/CookieBanner.scss
- src/components/CookieBanner/CookieBanner.tsx
- src/components/CookieBanner/index.ts
- src/types/global.d.ts
- tsconfig.json
> added cookie banner to website

- src/components/Footer/Footer.tsx
> added t&cs link to footer

- src/utils/events.ts
https://app.shortcut.com/ayup-digital-ltd/story/1006/update-frontend-app-to-be-configured-on-the-new-domain-name
Bugfix for typescript compile error
> Added ignore for typescript error

- aws/core.yml
- aws/lambda.yml
- package.json
- server.js
- src/components/Autocomplete/Autocomplete.tsx
- src/components/HomeScreenPrompt/HomeScreenPrompt.tsx
- src/components/LinkButton/LinkButton.tsx
- src/components/Select/Select.tsx
- src/components/StaticAutocomplete/StaticAutocomplete.tsx
- src/serviceWorker.js
- src/stores/referralStore.ts
- src/stores/resultsStore.ts
- src/stores/serviceStore.ts
- src/views/Referral/Steps/StepFive/Form.tsx
https://app.shortcut.com/ayup-digital-ltd/story/822/redeploy-frontend-infrastructure-to-allow-seo-friendliness
Add meta data to header using lambda edge function that runs on Cloudfront
> Hounslow sc 822 redeploy frontend infrastructure to allow

- aws/lambda.yml
https://app.shortcut.com/ayup-digital-ltd/story/822/redeploy-frontend-infrastructure-to-allow-seo-friendliness
Wrapped static meta in function to allow it to access global object after loading
> Wrapped static meta in function

- src/components/Header/Header.tsx
Story details: https://app.shortcut.com/ayup-digital-ltd/story/1938
> feat: [sc-1938] Add in "Events" to the global nav (Must)

- aws/lambda.yml
https://app.shortcut.com/ayup-digital-ltd/story/1957/seo-metadata-dynamic-title-description-must
- Added static seo meta data handler for `/events' index
- Added dynamic seo meta data handler for `/events/{event-id}` individual event
This work is untested as the urls in question are not yet created. This should be checked once they are in place.
> Updated lambda.yml to fetch SEO meta data for events

- src/components/Header/Header.tsx
https://app.shortcut.com/ayup-digital-ltd/story/1938/add-in-events-to-the-global-nav-must
Add in /events to the global nav must
> Hounslow sc 1938 add in events to the global nav must

- aws/lambda.yml
Reverts Hounslow-Connect/frontend#135
> Revert "Hounslow sc 1938 add in events to the global nav must"

- src/App.tsx
- src/components/EventFeed/EventFeed.tsx
- src/components/EventSummary/EventSummary.scss
- src/components/EventSummary/EventSummary.tsx
- src/hooks/useMediaQuery.ts
- src/stores/eventStore.ts
- src/views/Events/Events.scss
- src/views/Events/Events.tsx
- src/views/Events/index.ts
- src/views/Home/Home.tsx
- tslint.json
https://app.shortcut.com/ayup-digital-ltd/story/2031/create-events-search-results-page
Create main events page where we list all events. filtering to be added in next ticket. Fixed linter deprecation warning in this PR also
> Hounslow sc 2031 create events search results page

- src/App.tsx
- src/components/Button/Button.scss
- src/components/EventSummary/EventSummary.scss
- src/components/EventSummary/EventSummary.tsx
- src/components/Header/Header.tsx
- src/components/LinkButton/LinkButton.tsx
- src/index.js
- src/index.scss
- src/stores/eventStore.ts
- src/styles/colors.scss
- src/styles/generic-components.scss
- src/views/EventDetail/EventDetail.scss
- src/views/EventDetail/EventDetail.tsx
- src/views/EventDetail/index.ts
- src/views/Events/Events.scss
- src/views/Events/Events.tsx
- src/views/Service/CostCard/CostCard.tsx
- src/views/Service/LocationCard/LocationCard.tsx
- src/views/Service/Service.scss
- src/views/Service/Service.tsx
- src/views/Service/ShareCard/ShareCard.tsx
includes 1959 as we use same shared component
> Hounslow sc 2032 create events listing page template - Inc 1959 (social media)

- src/types/types.ts
- src/views/Service/ReferralCard/ReferralCard.tsx
- src/views/Service/Service.tsx
https://app.shortcut.com/ayup-digital-ltd/story/2604/bug-with-external-referrals
fixed bug with external referral type when clicking make connection button
> fixed bug with external referral type when clicking make connection button

- src/views/Service/LocationCard/LocationCard.tsx
Updated bank holiday opening times UI
> updated bank holiday opening times UI

- src/views/Service/LocationCard/LocationCard.tsx
> removed unused component import

- src/views/Events/Events.tsx
fixed bug with event search results
> fixed bug with event search results
